name = "netflix-release-cal"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-11-13"
kv_namespaces = [ 
    { binding = "KV_RELEASES", id = "1c8fcfef295b4bbab8cc680cf8882dee", preview_id = "1c8fcfef295b4bbab8cc680cf8882dee" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[triggers]
crons = ["0 0 * * sun"] # At 00:00 on Sunday.
